stages:
  preprocess_sklearn:
    cmd: python ../../features/preprocess_original_data.py
    deps:
    - ../../data/original
    outs:
    - ../../data/prepared:
        persist: true
  feature_generation_sklearn:
    cmd: python ../../features/handcrafted_features.py; python ../../features/morph_features.py
    deps:
    - ../../data/prepared
    outs:
    - ../../data/handcrafted:
        persist: true
    - ../../data/morph:
        persist: true
  fit_sklearn:
    cmd: python ../../models/sklearn/fit.py
    deps:
    - ../../data/handcrafted
    - ../../data/morph
    - ../../data/prepared
    outs:
    - ../../model_checkopoints/sklearn
    - ../../oof_predictions/sklearn:
        cache: false
    metrics:
    - ../../scores/scores_sklearn.json:
        cache: false
    plots:
    - ../../plots/sklearn/prc_0.json:
        cache: false
    - ../../plots/sklearn/prc_1.json:
        cache: false
    - ../../plots/sklearn/prc_2.json:
        cache: false
    - ../../plots/sklearn/prc_3.json:
        cache: false
    - ../../plots/sklearn/prc_4.json:
        cache: false
    - ../../plots/sklearn/prc_5.json:
        cache: false
    - ../../plots/sklearn/prc_6.json:
        cache: false
    - ../../plots/sklearn/prc_7.json:
        cache: false
    - ../../plots/sklearn/prc_8.json:
        cache: false
    - ../../plots/sklearn/roc_0.json:
        cache: false
    - ../../plots/sklearn/roc_1.json:
        cache: false
    - ../../plots/sklearn/roc_2.json:
        cache: false
    - ../../plots/sklearn/roc_3.json:
        cache: false
    - ../../plots/sklearn/roc_4.json:
        cache: false
    - ../../plots/sklearn/roc_5.json:
        cache: false
    - ../../plots/sklearn/roc_6.json:
        cache: false
    - ../../plots/sklearn/roc_7.json:
        cache: false
    - ../../plots/sklearn/roc_8.json:
        cache: false
    always_changed: true
  predict_sklearn:
    cmd: python ../../models/sklearn/predict.py
    deps:
    - ../../data/handcrafted
    - ../../data/morph
    - ../../data/prepared
    - ../../model_checkopoints/sklearn
    outs:
    - ../../test_predictions/sklearn:
        cache: false
    always_changed: true
