stages:
  fit_catboost_sbert_large_nlu_ru:
    cmd: python ../../models/catboost_sbert_large_nlu_ru/fit.py
    deps:
    - ../../data/prepared
    - ../../data/sbert_large_nlu_ru
    outs:
    - ../../model_checkopoints/catboost_sbert_large_nlu_ru:
        persist: true
    - ../../oof_predictions/catboost_sbert_large_nlu_ru:
        cache: false
        persist: true
    metrics:
    - ../../scores/scores_catboost_sbert_large_nlu_ru.json:
        cache: false
    plots:
    - ../../plots/catboost_sbert_large_nlu_ru/prc_0.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_1.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_2.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_3.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_4.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_5.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_6.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_7.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/prc_8.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_0.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_1.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_2.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_3.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_4.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_5.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_6.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_7.json:
        cache: false
    - ../../plots/catboost_sbert_large_nlu_ru/roc_8.json:
        cache: false
    always_changed: true
  predict_catboost_sbert_large_nlu_ru:
    cmd: python ../../models/catboost_sbert_large_nlu_ru/predict.py
    deps:
    - ../../data/prepared
    - ../../data/sbert_large_nlu_ru
    - ../../model_checkopoints/catboost_sbert_large_nlu_ru
    outs:
    - ../../test_predictions/catboost_sbert_large_nlu_ru:
        cache: false
        persist: true
    always_changed: true
  feature_generation_catboost_sbert_large_nlu_ru:
    cmd: echo pass
    deps:
    - ../../data/prepared
    outs:
    - ../../data/sbert_large_nlu_ru:
        persist: true
